[Definition]
failregex = ^<HOST> -.*"(?:GET|POST|HEAD|PUT|OPTIONS) [^"]*(?:\.env|/\.git|/wp-login\.php|/wp-admin|/xmlrpc\.php|/vendor/|/\.aws|/config\.php|/phpMyAdmin|/phpmyadmin|/\.ssh|/actuator|/solr/|/boaform|/\.vscode)[^"]*" .*$
ignoreregex =
