-- Migration 028: No conformidades en recepciones de compras
-- Detects and tracks quality/quantity non-conformities found during reception inspection.

-- Tabla principal de no conformidades
CREATE TABLE IF NOT EXISTS compras.no_conformidades (
  id                  bigserial PRIMARY KEY,
  codigo              varchar(20) NOT NULL UNIQUE,
  recepcion_id        bigint NOT NULL REFERENCES compras.recepciones(id),
  orden_compra_id     bigint REFERENCES compras.ordenes_compra(id),
  proveedor_id        bigint REFERENCES compras.proveedores(id),
  tipo                varchar(30) NOT NULL CHECK (tipo IN ('cantidad','calidad','documentacion','otro')),
  descripcion         text NOT NULL,
  accion_tomada       text,
  estado              varchar(20) NOT NULL DEFAULT 'abierta'
                      CHECK (estado IN ('abierta','en_proceso','cerrada')),
  responsable_id      uuid REFERENCES core.usuarios(id),
  fecha_cierre        timestamptz,
  costo_impacto       numeric(12,2),
  creado_por          uuid REFERENCES core.usuarios(id),
  actualizado_por     uuid REFERENCES core.usuarios(id),
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now()
);

-- Lineas afectadas de la recepcion
CREATE TABLE IF NOT EXISTS compras.nc_lineas (
  id                    bigserial PRIMARY KEY,
  no_conformidad_id     bigint NOT NULL REFERENCES compras.no_conformidades(id) ON DELETE CASCADE,
  recepcion_linea_id    bigint NOT NULL REFERENCES compras.recepcion_lineas(id),
  cantidad_no_conforme  numeric(12,3) NOT NULL,
  motivo                text,
  created_at            timestamptz NOT NULL DEFAULT now()
);

-- Indices
CREATE INDEX IF NOT EXISTS idx_nc_recepcion            ON compras.no_conformidades(recepcion_id);
CREATE INDEX IF NOT EXISTS idx_nc_proveedor            ON compras.no_conformidades(proveedor_id);
CREATE INDEX IF NOT EXISTS idx_nc_estado               ON compras.no_conformidades(estado);
CREATE INDEX IF NOT EXISTS idx_nc_lineas_nc            ON compras.nc_lineas(no_conformidad_id);
CREATE INDEX IF NOT EXISTS idx_nc_lineas_recepcion_linea ON compras.nc_lineas(recepcion_linea_id);

-- Trigger: updated_at automatico
CREATE TRIGGER tg_nc_updated_at
  BEFORE UPDATE ON compras.no_conformidades
  FOR EACH ROW EXECUTE FUNCTION core.fn_set_updated_at();

-- Trigger: auditoria (INSERT/UPDATE/DELETE -> core.audit_log)
CREATE TRIGGER tg_nc_auditar
  AFTER INSERT OR UPDATE OR DELETE ON compras.no_conformidades
  FOR EACH ROW EXECUTE FUNCTION core.fn_auditar();

-- Drop the now-unused sequence (code generated by trigger instead)
DROP SEQUENCE IF EXISTS compras.nc_seq_2026;

-- Trigger: codigo automatico NC-YYYY-NNNN
CREATE OR REPLACE FUNCTION compras.fn_generar_codigo_nc()
RETURNS TRIGGER LANGUAGE plpgsql AS $
DECLARE
  v_anio TEXT := TO_CHAR(NOW(), 'YYYY');
  v_max  INT;
BEGIN
  IF NEW.codigo IS NOT NULL AND LENGTH(NEW.codigo) > 0 THEN RETURN NEW; END IF;
  SELECT COALESCE(MAX(SPLIT_PART(codigo, '-', 3)::INTEGER), 0)
    INTO v_max FROM compras.no_conformidades
   WHERE codigo LIKE 'NC-' || v_anio || '-%';
  NEW.codigo := 'NC-' || v_anio || '-' || LPAD((v_max + 1)::TEXT, 4, '0');
  RETURN NEW;
END $;

CREATE TRIGGER tg_nc_codigo
  BEFORE INSERT ON compras.no_conformidades
  FOR EACH ROW EXECUTE FUNCTION compras.fn_generar_codigo_nc();

COMMENT ON TABLE compras.no_conformidades IS 'No conformidades detectadas en inspeccion de recepciones. Creadas automaticamente al marcar lineas como no_conforme o rechazado.';
COMMENT ON TABLE compras.nc_lineas IS 'Lineas individuales de recepcion afectadas por una no conformidad.';
