server {
    listen 80 default_server;
    server_name _;
    location /healthz { access_log off; return 200 "ok\n"; add_header Content-Type text/plain; }
    location / { return 444; }
}
server {
    listen 443 ssl http2 default_server;
    server_name _;
    ssl_certificate     /etc/letsencrypt/live/techtrafo.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/techtrafo.com/privkey.pem;
    return 444;
}
